services:
  ruby:
    build: .
    image: thisismydesign/blueprinter_schema:local
    command: sleep infinity
    volumes:
      - bundle_cache:/usr/local/bundle
      - .:/workspaces/blueprinter_schema:cached

volumes:
  bundle_cache:
